Merge QoL changes addressing #21
PaperFanz/insitu pull request #22
Opened 2021-10-13 18:42 UTC by PaperFanz

Changes:
- tutorial page on blank task view creation
- fix crashes from clicking random menu items
- start `insitu_utils` subpackage for common filter functions

2021-10-18 21:00 UTC, AdamPettinger reviewed
Looks good, with one minor detail. Will test quickly and approve

2021-10-18 21:00 UTC, AdamPettinger commented on insitu/src/main_window.cpp
> +    }
Excellent

2021-10-18 21:00 UTC, AdamPettinger commented on insitu_utils/package.xml
> +  <license>BSD</license>
This is public, we should fill these out

2021-10-18 21:20 UTC, AdamPettinger requested changes
Came across an issue building, probably from the recent merge. See suggestions.

Other few things:

- The top level CMakeLists links to `/opt/melodic/...`, not noetic
- When I pulled and built this, then did `roslaunch usb_cam usb_cam` and `rosrun insitu insitu`, I actually didn't get the tutorial page (just an empty insitu mode). Maybe that is because it was reading an old config file automatically. Eventually I did get the tutorial page by saving a new file (when the modes were empty) and when I reloaded it, the tutorials came up. Thoughts on this?

2021-10-18 21:20 UTC, AdamPettinger commented on insitu_utils/CMakeLists.txt
> +    inc
```suggestion
```

2021-10-18 21:20 UTC, AdamPettinger commented on insitu_utils/CMakeLists.txt
> +    INCLUDE_DIRS inc lib
```suggestion
    INCLUDE_DIRS lib
```

2021-10-19 04:08 UTC, PaperFanz commented
> 
> 
> Came across an issue building, probably from the recent merge. See suggestions.
> 
> Other few things:
> 
>     * The top level CMakeLists links to `/opt/melodic/...`, not noetic
> 
>     * When I pulled and built this, then did `roslaunch usb_cam usb_cam` and `rosrun insitu insitu`, I actually didn't get the tutorial page (just an empty insitu mode). Maybe that is because it was reading an old config file automatically. Eventually I did get the tutorial page by saving a new file (when the modes were empty) and when I reloaded it, the tutorials came up. Thoughts on this?

For the CMakeLists.txt, that will be fixed in a commit.

For the tutorial, that might be the case. It should be a simple fix. Thanks for catching that!

2021-10-20 15:31 UTC, PaperFanz reviewed
Should have addressed all the issues with the last two commits, @AdamPettinger could you re-review?

2021-10-20 16:46 UTC, AdamPettinger approved these changes
Looks great!

2021-10-20 17:14 UTC, merged